# This is a basic workflow to help you get started with Actions

name: Update image paths

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "workflow" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  fix-markdown-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: workflow 

      - name: Pull latest changes
        run: |
          git pull origin workflow
      - name: Fix image paths
        run: |
          repo_url="https://raw.githubusercontent.com/${{ github.repository }}/workflow/assets"  # Use `workflow` branch
          find . -name "*.md" | while read file; do
            sed -i -E "s#\!\[\[([^]]+)\]\]#\!\[\](${repo_url}/\1)#g" "$file"
            sed -i "s/ /%20/g" "$file"  # Encode spaces in URLs
          done
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Fix image paths for GitHub"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push
